[package]
name = "example-wasm-bindgen-free-of-stack-slot"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.95"
wasm-bindgen-test = "0.3.45"
